[project]
name = "gerador-de-qr-code"
version = "0.1.0"
description = "Aplicação simples em Python para geração automática de QR Codes exibidos no terminal com contagem regressiva."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "qrcode>=8.0",
    "pillow>=10.0.0",
]

[project.scripts]
gerador-de-qr-code = "gerador_de_qr_code:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"